# Generated by Django 2.1.1 on 2018-11-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181125_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
